//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.544
//     Generated on:    11/05/2012 3:41:19 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace SharpGpx.GPX1_1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute("gpx", Namespace="http://www.topografix.com/GPX/1/1", IsNullable=false)]
    public partial class gpxType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public gpxType() {
            this.versionField = "1.1";
        }
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private metadataType metadataField;
        
        /// <remarks/>
        public metadataType metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <summary />
        private wptTypeCollection wptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wpt")]
        public wptTypeCollection wpt {
            get {
                return this.wptField;
            }
            set {
                this.wptField = value;
                this.RaisePropertyChanged("wpt");
            }
        }
        
        /// <summary />
        private rteTypeCollection rteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rte")]
        public rteTypeCollection rte {
            get {
                return this.rteField;
            }
            set {
                this.rteField = value;
                this.RaisePropertyChanged("rte");
            }
        }
        
        /// <summary />
        private trkTypeCollection trkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trk")]
        public trkTypeCollection trk {
            get {
                return this.trkField;
            }
            set {
                this.trkField = value;
                this.RaisePropertyChanged("trk");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
        
        /// <summary />
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <summary />
        private string creatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("creator");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class metadataType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string descField;
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <summary />
        private personType authorField;
        
        /// <remarks/>
        public personType author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <summary />
        private copyrightType copyrightField;
        
        /// <remarks/>
        public copyrightType copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
                this.RaisePropertyChanged("copyright");
            }
        }
        
        /// <summary />
        private linkTypeCollection linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public linkTypeCollection link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <summary />
        private System.DateTime timeField;
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <summary />
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        /// <summary />
        private string keywordsField;
        
        /// <remarks/>
        public string keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("keywords");
            }
        }
        
        /// <summary />
        private boundsType boundsField;
        
        /// <remarks/>
        public boundsType bounds {
            get {
                return this.boundsField;
            }
            set {
                this.boundsField = value;
                this.RaisePropertyChanged("bounds");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class personType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private emailType emailField;
        
        /// <remarks/>
        public emailType email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <summary />
        private linkType linkField;
        
        /// <remarks/>
        public linkType link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class emailType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <summary />
        private string domainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class trksegType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private wptTypeCollection trkptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trkpt")]
        public wptTypeCollection trkpt {
            get {
                return this.trkptField;
            }
            set {
                this.trkptField = value;
                this.RaisePropertyChanged("trkpt");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class wptType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal eleField;
        
        /// <remarks/>
        public decimal ele {
            get {
                return this.eleField;
            }
            set {
                this.eleField = value;
                this.RaisePropertyChanged("ele");
            }
        }
        
        /// <summary />
        private bool eleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified {
            get {
                return this.eleFieldSpecified;
            }
            set {
                this.eleFieldSpecified = value;
                this.RaisePropertyChanged("eleSpecified");
            }
        }
        
        /// <summary />
        private System.DateTime timeField;
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <summary />
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        /// <summary />
        private decimal magvarField;
        
        /// <remarks/>
        public decimal magvar {
            get {
                return this.magvarField;
            }
            set {
                this.magvarField = value;
                this.RaisePropertyChanged("magvar");
            }
        }
        
        /// <summary />
        private bool magvarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified {
            get {
                return this.magvarFieldSpecified;
            }
            set {
                this.magvarFieldSpecified = value;
                this.RaisePropertyChanged("magvarSpecified");
            }
        }
        
        /// <summary />
        private decimal geoidheightField;
        
        /// <remarks/>
        public decimal geoidheight {
            get {
                return this.geoidheightField;
            }
            set {
                this.geoidheightField = value;
                this.RaisePropertyChanged("geoidheight");
            }
        }
        
        /// <summary />
        private bool geoidheightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified {
            get {
                return this.geoidheightFieldSpecified;
            }
            set {
                this.geoidheightFieldSpecified = value;
                this.RaisePropertyChanged("geoidheightSpecified");
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string cmtField;
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
                this.RaisePropertyChanged("cmt");
            }
        }
        
        /// <summary />
        private string descField;
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <summary />
        private string srcField;
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
                this.RaisePropertyChanged("src");
            }
        }
        
        /// <summary />
        private linkTypeCollection linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public linkTypeCollection link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <summary />
        private string symField;
        
        /// <remarks/>
        public string sym {
            get {
                return this.symField;
            }
            set {
                this.symField = value;
                this.RaisePropertyChanged("sym");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private fixType fixField;
        
        /// <remarks/>
        public fixType fix {
            get {
                return this.fixField;
            }
            set {
                this.fixField = value;
                this.RaisePropertyChanged("fix");
            }
        }
        
        /// <summary />
        private bool fixFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified {
            get {
                return this.fixFieldSpecified;
            }
            set {
                this.fixFieldSpecified = value;
                this.RaisePropertyChanged("fixSpecified");
            }
        }
        
        /// <summary />
        private string satField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string sat {
            get {
                return this.satField;
            }
            set {
                this.satField = value;
                this.RaisePropertyChanged("sat");
            }
        }
        
        /// <summary />
        private decimal hdopField;
        
        /// <remarks/>
        public decimal hdop {
            get {
                return this.hdopField;
            }
            set {
                this.hdopField = value;
                this.RaisePropertyChanged("hdop");
            }
        }
        
        /// <summary />
        private bool hdopFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified {
            get {
                return this.hdopFieldSpecified;
            }
            set {
                this.hdopFieldSpecified = value;
                this.RaisePropertyChanged("hdopSpecified");
            }
        }
        
        /// <summary />
        private decimal vdopField;
        
        /// <remarks/>
        public decimal vdop {
            get {
                return this.vdopField;
            }
            set {
                this.vdopField = value;
                this.RaisePropertyChanged("vdop");
            }
        }
        
        /// <summary />
        private bool vdopFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified {
            get {
                return this.vdopFieldSpecified;
            }
            set {
                this.vdopFieldSpecified = value;
                this.RaisePropertyChanged("vdopSpecified");
            }
        }
        
        /// <summary />
        private decimal pdopField;
        
        /// <remarks/>
        public decimal pdop {
            get {
                return this.pdopField;
            }
            set {
                this.pdopField = value;
                this.RaisePropertyChanged("pdop");
            }
        }
        
        /// <summary />
        private bool pdopFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified {
            get {
                return this.pdopFieldSpecified;
            }
            set {
                this.pdopFieldSpecified = value;
                this.RaisePropertyChanged("pdopSpecified");
            }
        }
        
        /// <summary />
        private decimal ageofdgpsdataField;
        
        /// <remarks/>
        public decimal ageofdgpsdata {
            get {
                return this.ageofdgpsdataField;
            }
            set {
                this.ageofdgpsdataField = value;
                this.RaisePropertyChanged("ageofdgpsdata");
            }
        }
        
        /// <summary />
        private bool ageofdgpsdataFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified {
            get {
                return this.ageofdgpsdataFieldSpecified;
            }
            set {
                this.ageofdgpsdataFieldSpecified = value;
                this.RaisePropertyChanged("ageofdgpsdataSpecified");
            }
        }
        
        /// <summary />
        private string dgpsidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string dgpsid {
            get {
                return this.dgpsidField;
            }
            set {
                this.dgpsidField = value;
                this.RaisePropertyChanged("dgpsid");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
        
        /// <summary />
        private decimal latField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <summary />
        private decimal lonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
                this.RaisePropertyChanged("lon");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class linkType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string textField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public enum fixType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2d")]
        Item2d,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3d")]
        Item3d,
        
        /// <remarks/>
        dgps,
        
        /// <remarks/>
        pps,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class extensionsType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        [System.NonSerialized()]
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class trkType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string cmtField;
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
                this.RaisePropertyChanged("cmt");
            }
        }
        
        /// <summary />
        private string descField;
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <summary />
        private string srcField;
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
                this.RaisePropertyChanged("src");
            }
        }
        
        /// <summary />
        private linkTypeCollection linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public linkTypeCollection link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
        
        /// <summary />
        private trksegTypeCollection trksegField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trkseg")]
        public trksegTypeCollection trkseg {
            get {
                return this.trksegField;
            }
            set {
                this.trksegField = value;
                this.RaisePropertyChanged("trkseg");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class rteType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <summary />
        private string cmtField;
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
                this.RaisePropertyChanged("cmt");
            }
        }
        
        /// <summary />
        private string descField;
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <summary />
        private string srcField;
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
                this.RaisePropertyChanged("src");
            }
        }
        
        /// <summary />
        private linkTypeCollection linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public linkTypeCollection link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <summary />
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <summary />
        private string typeField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
        
        /// <summary />
        private wptTypeCollection rteptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rtept")]
        public wptTypeCollection rtept {
            get {
                return this.rteptField;
            }
            set {
                this.rteptField = value;
                this.RaisePropertyChanged("rtept");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class boundsType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal minlatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlat {
            get {
                return this.minlatField;
            }
            set {
                this.minlatField = value;
                this.RaisePropertyChanged("minlat");
            }
        }
        
        /// <summary />
        private decimal minlonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal minlon {
            get {
                return this.minlonField;
            }
            set {
                this.minlonField = value;
                this.RaisePropertyChanged("minlon");
            }
        }
        
        /// <summary />
        private decimal maxlatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlat {
            get {
                return this.maxlatField;
            }
            set {
                this.maxlatField = value;
                this.RaisePropertyChanged("maxlat");
            }
        }
        
        /// <summary />
        private decimal maxlonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal maxlon {
            get {
                return this.maxlonField;
            }
            set {
                this.maxlonField = value;
                this.RaisePropertyChanged("maxlon");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class copyrightType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <summary />
        private string licenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
                this.RaisePropertyChanged("license");
            }
        }
        
        /// <summary />
        private string authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class ptType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal eleField;
        
        /// <remarks/>
        public decimal ele {
            get {
                return this.eleField;
            }
            set {
                this.eleField = value;
                this.RaisePropertyChanged("ele");
            }
        }
        
        /// <summary />
        private bool eleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified {
            get {
                return this.eleFieldSpecified;
            }
            set {
                this.eleFieldSpecified = value;
                this.RaisePropertyChanged("eleSpecified");
            }
        }
        
        /// <summary />
        private System.DateTime timeField;
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <summary />
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        /// <summary />
        private decimal latField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <summary />
        private decimal lonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
                this.RaisePropertyChanged("lon");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=true)]
    public partial class ptsegType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private ptTypeCollection ptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pt")]
        public ptTypeCollection pt {
            get {
                return this.ptField;
            }
            set {
                this.ptField = value;
                this.RaisePropertyChanged("pt");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class wptTypeCollection : System.Collections.Generic.List<wptType> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class rteTypeCollection : System.Collections.Generic.List<rteType> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trkTypeCollection : System.Collections.Generic.List<trkType> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class linkTypeCollection : System.Collections.Generic.List<linkType> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trksegTypeCollection : System.Collections.Generic.List<trksegType> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class ptTypeCollection : System.Collections.Generic.List<ptType> {
    }
}
#pragma warning restore 1591